project_id = "vnvphfrrmoaskiwlspeo"

[functions.send-contact-email]
verify_jwt = false

[functions.send-analysis-email]
verify_jwt = false

[functions.track-partner-click]
verify_jwt = false

[functions.submit-change-request]
verify_jwt = false
