project_id = "vnvphfrrmoaskiwlspeo"

[functions.send-contact-email]
verify_jwt = false

[functions.send-analysis-email]
verify_jwt = false

[functions.track-partner-click]
verify_jwt = false

[functions.submit-lead]
verify_jwt = false

[functions.admin-login]
verify_jwt = false

[functions.manage-leads]
verify_jwt = false

[functions.manage-partners]
verify_jwt = false

[functions.import-partners]
verify_jwt = false
