// AUTO-GENERATED by @lovable.dev/mcp-js – do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-partners.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
function supabaseAnon() {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } });
}
var search_partners_default = defineTool({
  name: "search_partners",
  title: "S\xF6k Dynamics 365-partners",
  description: "S\xF6k publika, publicerade Dynamics 365-partners p\xE5 d365.se. Filtrera p\xE5 applikation (t.ex. 'Business Central', 'Finance & Supply Chain', 'Sales', 'Customer Service'), bransch och geografi. Returnerar namn, kort beskrivning, applikationer, branscher, geografi och publik profil-URL.",
  inputSchema: {
    application: z.string().optional().describe("Dynamics 365-applikation att filtrera p\xE5."),
    industry: z.string().optional().describe("Bransch (t.ex. 'Tillverkning', 'Detaljhandel')."),
    geography: z.string().optional().describe("Geografi (t.ex. 'Sverige', 'Norden')."),
    limit: z.number().int().min(1).max(50).optional().describe("Max antal resultat (1-50, default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ application, industry, geography, limit }) => {
    const sb = supabaseAnon();
    let q = sb.from("partners_public").select("slug,name,description,applications,industries,geography,office_cities,website").eq("is_featured", true).limit(limit ?? 20);
    if (application) q = q.contains("applications", [application]);
    if (industry) q = q.contains("industries", [industry]);
    if (geography) q = q.contains("geography", [geography]);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: `Fel: ${error.message}` }], isError: true };
    }
    const rows = (data ?? []).map((p) => ({
      ...p,
      profile_url: `https://d365.se/partner/${p.slug}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { partners: rows, count: rows.length }
    };
  }
});

// src/lib/mcp/tools/get-partner.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseAnon2() {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient2(url, key, { auth: { persistSession: false, autoRefreshToken: false } });
}
var get_partner_default = defineTool2({
  name: "get_partner",
  title: "H\xE4mta partnerprofil",
  description: "H\xE4mta den publika profilen f\xF6r en enskild Dynamics 365-partner p\xE5 d365.se via slug (t.ex. 'cgi', 'columbus'). Returnerar beskrivning, applikationer, branscher, geografi, kontor, kundexempel och positioneringsinformation.",
  inputSchema: {
    slug: z2.string().min(1).describe("Partnerns URL-slug, t.ex. 'columbus'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const sb = supabaseAnon2();
    const { data, error } = await sb.from("partners_public").select(
      "slug,name,description,website,applications,industries,secondary_industries,geography,office_cities,customer_examples,positioning_statement,team_size_sweden,implementations_done,ai_summary"
    ).eq("slug", slug).eq("is_featured", true).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: `Fel: ${error.message}` }], isError: true };
    }
    if (!data) {
      return {
        content: [{ type: "text", text: `Ingen publicerad partner hittades f\xF6r slug '${slug}'.` }],
        isError: true
      };
    }
    const enriched = { ...data, profile_url: `https://d365.se/partner/${data.slug}` };
    return {
      content: [{ type: "text", text: JSON.stringify(enriched, null, 2) }],
      structuredContent: enriched
    };
  }
});

// src/lib/mcp/tools/list-knowledge-articles.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseAnon3() {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient3(url, key, { auth: { persistSession: false, autoRefreshToken: false } });
}
var list_knowledge_articles_default = defineTool3({
  name: "list_knowledge_articles",
  title: "Lista kunskapsartiklar",
  description: "Lista publicerade artiklar fr\xE5n d365.se kunskapscenter. Filtrera fritt p\xE5 \xE4mne via 'query' som matchar titel eller sammanfattning.",
  inputSchema: {
    query: z3.string().optional().describe("Fritexts\xF6kning i titel/sammanfattning."),
    limit: z3.number().int().min(1).max(50).optional().describe("Max antal resultat (1-50, default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const sb = supabaseAnon3();
    let q = sb.from("knowledge_articles").select("slug,title,summary,category,published_at").not("published_at", "is", null).order("published_at", { ascending: false }).limit(limit ?? 20);
    if (query && query.trim()) {
      const term = `%${query.trim()}%`;
      q = q.or(`title.ilike.${term},summary.ilike.${term}`);
    }
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: `Fel: ${error.message}` }], isError: true };
    }
    const rows = (data ?? []).map((a) => ({
      ...a,
      url: `https://d365.se/kunskapscenter/${a.slug}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { articles: rows, count: rows.length }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "d365-guide-mcp",
  title: "D365 Guide MCP",
  version: "0.1.0",
  instructions: "Verktyg f\xF6r d365.se \u2013 Svenska guiden till Microsoft Dynamics 365. Anv\xE4nd 'search_partners' f\xF6r att hitta certifierade svenska D365-implementeringspartners filtrerat p\xE5 applikation, bransch och geografi. Anv\xE4nd 'get_partner' f\xF6r att h\xE4mta en enskild partnerprofil via slug. Anv\xE4nd 'list_knowledge_articles' f\xF6r att hitta publicerade artiklar i kunskapscentret. All data \xE4r publik och k\xF6parsidig \u2013 f\xF6lj TAYA-principen om radikal transparens.",
  tools: [search_partners_default, get_partner_default, list_knowledge_articles_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
