UPDATE partners SET ai_summary_full = 'Bisqo AB specialiserar sig på att implementera och konfigurera Dynamics 365 Business Central för medelstora företag. Partnerns erbjudande bygger på standardiserade system och paketlösningar, med målet att tillhandahålla en snabb och förutsägbar leverans med tydlig omfattning. Deras arbetssätt betonar beprövade metoder för att säkerställa effektiv ekonomistyrning och skalbarhet för kunden.

Fokus ligger på medelstora grossist-, distributions- och tillverkningsföretag i Norden. Bisqo positionerar sig som en partner för organisationer som söker effektiv affärsstyrning i Business Central och som värdesätter ett paketerat erbjudande med fast pris och fast scope. De framhåller sin kombination av affärsförståelse och teknisk kompetens för att skapa verkligt affärsvärde snarare än enbart ett system.

Partnern hanterar implementering och konfiguration av Dynamics 365 Business Central. De ser lösningen som en del av ett ekosystem som kan inkludera CRM på Power Platform. Deras expertis omfattar att effektivisera affärsprocesser genom dessa standardlösningar och anpassa dem till kundens unika behov. De har kompetens i att utnyttja befintlig funktionalitet för skalbarhet och framtidssäkring.

När det gäller AI och Copilot arbetar Bisqo med att implementera standardlösningar för att effektivisera affärsprocesser inom Business Central och Power Platform. De lämpar sig för organisationer som söker rådgivning och workshops för att nyttja befintlig funktionalitet för skalbarhet och framtidssäkring. Partnern har en deklarerad rådgivande erfarenhetsnivå inom AI-området.', best_fit_for = ARRAY['Partnern passar organisationer med 50 till 999 anställda som verkar inom grossist- och distributionssektorn.', 'Bisqo AB är ett lämpligt val för företag inom tillverkningsindustrin som söker effektiv affärsstyrning.', 'Organisationer som prioriterar standardiserade och paketerade implementeringar av Dynamics 365 Business Central kan finna Bisqo lämplig.', 'Partnern är inriktad på nordiska företag, särskilt medelstora, som behöver affärssystemstöd.', 'Företag som söker en leverantör med kompetens inom Dynamics 365 Business Central kan vända sig till Bisqo AB.', 'Kunder som uppskattar projekt med fast pris och fast scope för Business Central-implementeringar är en god matchning för Bisqo AB.', 'Verksamheter som vill effektivisera sina ekonomiprocesser med Microsofts lösningar kan ha nytta av Bisqo AB:s kompetens.', 'Organisationer som har behov av rådgivning kring befintlig funktionalitet för skalbarhet och framtidssäkring inom Business Central kan vara lämpliga kunder.']::text[], ai_tags = ARRAY['Business Central', 'Grossist', 'Distribution', 'Tillverkning', 'Retail', 'E-handel', 'CRM', 'ERP', 'Affärsprocesser', 'Standardlösningar', 'Paketlösningar', 'Implementering', 'Konfiguration', 'Ekonomistyrning', 'Skalbarhet', 'Norden', 'AI-rådgivning', 'Power Platform']::text[] WHERE id = 'd51765db-7ab6-4cb6-8c53-384f1ffee552';
UPDATE partners SET ai_summary_full = 'Fellowmind är en europeisk Microsoft-partner med närvaro i flera länder, som arbetar med en bred kundbas. Partnern fokuserar på att kombinera djup branschkunskap med specialistkompetens inom molnbaserad teknologi och hela Microsoft-plattformen. De har en tydlig inriktning på långsiktiga partnerskap och att sätta människan i centrum för sina lösningar.

Partnerns produktfokus innefattar Dynamics 365 Business Central, Dynamics 365 Finance, Dynamics 365 Supply Chain Management, Dynamics 365 Sales och Dynamics 365 Customer Insights. De erbjuder omfattande stöd för dessa applikationer, från analys och implementation till anpassning, uppgradering och löpande support genom hela projektets livscykel. Fellowmind har kompetens att integrera olika Dynamics 365-applikationer för att skapa sammanhängande affärssystem.

Fellowmind arbetar med kunder i branscher som grossist och distribution, konsulttjänster, retail och e-handel, tillverkningsindustri, life science/medtech samt fastighet och förvaltning. De har erfarenhet av att optimera processer inom bland annat ekonomi, produktion, logistik, lagerhantering, försäljning och kundrelationer. Kundstorleken varierar från medelstora till större företag med omsättning från 25 MSEK upp till 4 999 MSEK, samt anställda från 50 upp till 999.

Partnerns arbetssätt bygger på att leverera datadriven verksamhetsstyrning och att skapa skalbara lösningar. De betonar vikten av att effektivisera verksamhetsmetodik och processer genom att utnyttja Dynamics 365-applikationernas funktionalitet. Implementeringar av D365 Sales och Customer Insights sker med fokus på CRM, kunddata, automation och AI för att förbättra kundupplevelser genom hela kundresan.

Fellowmind integrerar Microsofts standard AI-lösningar, inklusive Copilot Studio och inbyggda Copilot-funktioner, primärt inom Business Central-miljöer. Denna tekniska kompetens inom AI är inriktad på att förstärka befintliga processer med beprövade AI-funktioner. Partnern bistår organisationer som vill implementera eller optimera dessa funktioner för att uppnå omedelbara fördelar inom sina verksamheter.', best_fit_for = ARRAY['Organisationer inom grossist och distribution, konsulttjänster, retail och e-handel som behöver implementera eller optimera Dynamics 365 Business Central.', 'Företag med en omsättning mellan 100 och 4 999 MSEK som söker stöd för Dynamics 365 Finance & Supply Chain Management.', 'Tillverkande bolag och företag inom life science/medtech som vill effektivisera sin ekonomi, produktion och logistik med Dynamics 365 Finance & Supply Chain Management.', 'Organisationer inom fastighet och förvaltning, tillverkning och konsulttjänster med 50 till 999 anställda som behöver implementera Dynamics 365 Sales eller Customer Insights.', 'Bolag som efterfrågar en partner med expertis inom CRM, kunddata, automation och AI för att skapa bättre kundupplevelser genom hela kundresan.', 'Kunder som söker en partner med förmåga att hantera internationella utrullningar av Dynamics 365-lösningar.', 'Företag som vill integrera Microsofts standard AI-lösningar, inklusive Copilot Studio och inbyggd Copilot, i befintliga Business Central-miljöer.', 'Organisationer som prioriterar en partner med fokus på långsiktiga partnerskap och stöd genom hela projektets livscykel, från analys till driftsättning och support.', 'Kunder som har behov av implementeringstjänster avseende Microsofts molnplattform.', 'Bolag som har behov av att effektivisera sin verksamhet i Sverige eller internationellt.']::text[], ai_tags = ARRAY['Dynamics 365 Business Central', 'Dynamics 365 Finance', 'Dynamics 365 Supply Chain Management', 'Dynamics 365 Sales', 'Dynamics 365 Customer Insights', 'Grossist', 'Distribution', 'Konsulttjänster', 'Retail', 'E-handel', 'Tillverkningsindustri', 'Life Science', 'Medtech', 'Fastighet', 'Förvaltning', 'CRM', 'Säljstöd', 'Ekonomi', 'Logistik', 'Lagerhantering', 'Produktion', 'Leveranskedja', 'Affärssystem', 'Verksamhetsoptimering', 'Implementation', 'Support', 'Molnbaserade lösningar', 'Copilot Studio', 'Inbyggd Copilot', 'AI', 'Internationella projekt']::text[] WHERE id = '42f8b63b-a4c9-480d-81e5-a322652b3af4';
UPDATE partners SET ai_summary_full = 'Goodfellows fokuserar på implementering och förvaltning av Dynamics 365 Business Central. Partnern erbjuder stöd genom hela livscykeln, från förstudie till långsiktig support, och betonar kontinuitet genom att samma konsulter följer kunden över tid. Detta arbetssätt syftar till att säkerställa en djup förståelse för kundens processer och affärskritiska behov.

Goodfellows typiska kundbas består av medelstora företag. Branscherfarenheten är koncentrerad till områden som grossist- och distribution, retail och e-handel, samt konsulttjänster. Företaget bidrar med affärsförståelse inom dessa sektorer för att styra mot lösningar som skapar affärsnytta. Leveransmodellen syftar till att erbjuda en förutsägbar prisbild och en process utan överraskningar.

Den tekniska kompetensen är inriktad mot Dynamics 365 Business Central, inklusive standardfunktionalitet och anpassningar inom systemets ramar. Partnern specificerar att de inte är lämpade för projekt som kräver omfattande egenutveckling utanför standardfunktionaliteten.

Goodfellows adresserar AI-kompetens genom att implementera Copilot Studio och standardiserade AI-funktioner inom Business Central. De positionerar sig för organisationer som önskar att förstärka sina processer med Microsofts färdiga AI-lösningar och anpassade agenter i Business Central.', best_fit_for = ARRAY['Organisationer som efterfrågar långsiktigt stöd och kontinuitet med samma konsulter för Dynamics 365 Business Central.', 'Medelstora företag i grossist- och distributionsbranschen som söker implementering och förvaltning av Dynamics 365 Business Central.', 'Detaljhandelsföretag och e-handelsaktörer som behöver en partner med erfarenhet av Dynamics 365 Business Central.', 'Konsulttjänstföretag som önskar en Dynamics 365 Business Central-lösning anpassad för deras specifika processer.', 'Företag med 1 till 249 anställda som söker en partner med förutsägbar leveransmodell för Dynamics 365 Business Central.', 'Organisationer som vill implementera eller förstärka sina processer med standardiserade AI-funktioner och Copilot Studio inom Dynamics 365 Business Central.', 'Kunder som prioriterar partnerkontinuitet för sin Dynamics 365 Business Central-miljö.', 'Företag som söker en partner för Dynamics 365 Business Central-projekt med fokus på standardfunktionalitet snarare än omfattande egenutveckling.']::text[], ai_tags = ARRAY['Dynamics 365 Business Central', 'Grossist', 'Distribution', 'Retail', 'E-handel', 'Konsulttjänster', 'Medelstora företag', 'Implementering', 'Förvaltning', 'Support', 'Kontinuitet', 'Affärssystem', 'Microsoft Copilot Studio', 'AI', 'Standard-AI', 'Säljprocesser', 'Ekonomistyrning', 'Lagerhantering', 'Logistik', 'Göteborg']::text[] WHERE id = '731f9c05-c293-4842-ac40-19fb610eaeac';
UPDATE partners SET ai_summary_full = 'InBiz är en partner med inriktning mot Microsoft Dynamics 365 Business Central, med en historik av systemimplementering och förvaltning sedan 2005. Partnern fokuserar på att leverera lösningar som skapar effektiva affärsprocesser, särskilt inom områden som logistikoptimering och finansiell styrning. InBiz har ett uttalat långsiktigt perspektiv i sina kundrelationer, med fokus på löpande utveckling och förvaltning av Business Central-miljöer.

Partnerns primära kundsegment återfinns inom tillverkningsindustrin, grossist- och distributionsbranschen samt livsmedels- och processindustrin. Partnern samarbetar även med konsultbolag och har sitt kontor i Uppsala. Det tillgängliga underlaget indikerar att InBiz riktar sig mot företag med behov av anpassade Business Central-system för att hantera specifika processkrav inom sina kärnbranscher.

InBiz erbjuder kompetens inom anpassning av Business Central för att möta kundspecifika verksamhetsbehov. Partnern är en del av Companial-nätverket, vilket indikerar tillgång till en bredd inom Microsofts ekosystem. Den tekniska kompetensen är centrerad kring Business Central och dess integration med kundanpassade lösningar.

Vad gäller AI och Copilot, erbjuder InBiz vägledning och workshops för att förbereda kunders system och data för framtida AI-integrationer. Partnerns AI-kompetens definieras som rådgivande, med fokus på AI-beredskap och datakvalitet, särskilt inför Copilot-integration i Business Central. Denna kompetens är organiserad via ett centralt team och riktar sig till företag som önskar effektivisera sina ERP-processer med AI.', best_fit_for = ARRAY['Organisationer inom tillverkningsindustrin med behov av anpassade Business Central-system för att optimera processer.', 'Grossist- och distributionsföretag som söker en partner med erfarenhet av Business Central för effektiv logistik och finansiell styrning.', 'Företag inom livsmedels- och processindustrin som behöver stöd med implementering och förvaltning av Business Central.', 'Kunder som prioriterar en partner med lång erfarenhet av Business Central och ett långsiktigt perspektiv på systemförvaltning.', 'Verksamheter som är belägna i eller omkring Uppsala, eller som föredrar en partner med lokal förankring i Sverige.', 'Företag som önskar rådgivning kring AI-beredskap och datakvalitet inför potentiell integration av Copilot med Business Central.', 'Organisationer som har anställda i spannet 1-999 och söker en partner som kan anpassa Business Central för deras specifika behov.']::text[], ai_tags = ARRAY['Dynamics 365 Business Central', 'Tillverkningsindustri', 'Grossist', 'Distribution', 'Livsmedelsindustri', 'Processindustri', 'ERP-system', 'Systemimplementering', 'Systemförvaltning', 'Logistikoptimering', 'Finansiell styrning', 'Processhantering', 'Anpassade lösningar', 'AI-beredskap', 'Datakvalitet', 'Copilot-integration', 'Sverige', 'Uppsala', 'Små och medelstora företag', 'Business Central-anpassning', 'Långsiktigt partnerskap', 'Companial-nätverket']::text[] WHERE id = '47db240f-0e3c-4ef7-8532-ddd914a990de';