ALTER TABLE public.partners ADD COLUMN IF NOT EXISTS key_differentiators_source text NOT NULL DEFAULT 'partner';
ALTER TABLE public.partner_submissions ADD COLUMN IF NOT EXISTS key_differentiators_source text NOT NULL DEFAULT 'partner';

UPDATE public.partners SET key_differentiators_source = 'd365', key_differentiators = v.kd
FROM (VALUES
 ('4PS Construction Software AB', ARRAY['Branschlösningen 4PS Construct är byggd på Dynamics 365 Business Central','Inriktning mot bygg, entreprenad, installation och service','Stöd för projekt, kalkyl, inköp, resursplanering och fältservice i samma system','Kontor i Norrköping och Göteborg']),
 ('adbriq', ARRAY['Business Central-specialist med inriktning mot mode, sport, textil, retail och e-handel','Arbetar med TRIMIT Fashion för artikelvarianter, kollektioner och produktdata','Stöd för lager och integrationer mot handelsflöden','Verksamhet från Borås']),
 ('B3 Elevate', ARRAY['Renodlat fokus på Dynamics 365 Customer Engagement: Sales, Customer Insights, Customer Service, Field Service och Contact Center','Dokumenterat arbete med medlemsorganisationer','Arbetar med AI och automation i sälj- och serviceprocesser','Del av B3 Consulting Group, team i Stockholm om 11–25 personer']),
 ('BE-terna', ARRAY['Finance & Supply Chain Management som kärnområde','Inriktning mot tillverkning, grossist/distribution och retail','Kapacitet för internationella ERP-projekt med europeisk närvaro','Kontor i Halmstad och Helsingborg']),
 ('Bisqo AB', ARRAY['Business Central i kombination med CRM på Power Platform och Power BI','Paketerade och standardiserade implementationer','Inriktning mot medelstora grossist-, distributions- och tillverkningsföretag','Kontor i Malmö och Helsingborg, team om 11–25 personer']),
 ('CRMK (CRM-Konsulterna)', ARRAY['Specialiserat på Dynamics 365 Customer Engagement utan ERP-leverans','Arbetar med Power Apps, Power Automate och Copilot Studio','Erfarenhet från finans och försäkring, medlemsorganisationer, life science och non-profit','Kontor i Stockholm och Kalmar, team om 11–25 personer']),
 ('Fellowmind', ARRAY['Levererar både Business Central, Finance & Supply Chain Management och Customer Engagement','Passar organisationer som vill kombinera ERP, CRM och data i Microsoft-plattformen','Sju kontorsorter i Sverige','Över 50 medarbetare i Sverige']),
 ('InBiz', ARRAY['Business Central-specialist utan bredare produktportfölj','Erfarenhet från tillverkning, grossist/distribution samt livsmedel och processindustri','Implementation, vidareutveckling och förvaltning i samma team','Verksamhet från Uppsala, team om 1–10 personer']),
 ('Knowit', ARRAY['Fokus på Finance & Supply Chain Management för medelstora och större verksamheter','Erfarenhet av komplexa integrationer och internationella koncernmiljöer','Kundcase inom tillverkning, grossist/distribution, energi och handel','Kontor i Stockholm, Göteborg och Malmö']),
 ('Modia', ARRAY['Business Central-specialist utan bredare produktportfölj','Samma konsulter följer kunden från förstudie till förvaltning','Erfarenhet från grossist/distribution, handel, e-handel och produktion','Verksamhet från Göteborg']),
 ('NAB Solutions', ARRAY['Business Central som kärnområde med tillägg av Dynamics 365 för sälj, marknad och service','Lång erfarenhet av Microsofts ERP-plattform','Erfarenhet från grossist/distribution, tillverkning och uthyrningsverksamhet','Fem kontorsorter och över 50 medarbetare i Sverige']),
 ('Nexer', ARRAY['Bred Dynamics 365-portfölj med Business Central, Customer Engagement och Project Operations','Svensk och internationell leveranskapacitet','Erfarenhet från tillverkning, grossist/distribution och retail','Sex kontorsorter och över 50 medarbetare i Sverige']),
 ('Point Taken', ARRAY['Renodlat Customer Engagement med tyngdpunkt på Sales och Customer Service','Kompetens även inom Customer Insights, Field Service och Contact Center','Tydligast målgrupp är konsulttjänsteföretag och medelstora organisationer','Mindre team i Stockholm, 1–10 personer']),
 ('Sherpas Group AB', ARRAY['Levererar både Business Central och Finance & Supply Chain Management','Erfarenhet inom tillverkning, energi, logistik samt bygg och entreprenad','Följer kunden från förstudie till integration, support och uppgradering','Kontor i Skellefteå och Stockholm, över 50 medarbetare']),
 ('Sirocco Group', ARRAY['Customer Engagement-partner med Sales, Customer Insights, Customer Service, Field Service och Contact Center','Levererar även Project Operations för uppdragsstyrd verksamhet','Dokumenterad erfarenhet inom tillverkning och livsmedels-/processindustri','Verksamhet från Stockholm']),
 ('Vivicta', ARRAY['Mycket brett Dynamics 365-erbjudande: Finance, Supply Chain Management, Business Central, Customer Engagement och Human Resources','Inriktning mot verksamheter med komplexa processer inom industri, transport och energi','Erfarenhet från offentlig sektor, skogs- och processindustri','Åtta kontorsorter i Sverige']),
 ('Yellow Solution AB', ARRAY['Business Central-specialist utan bredare produktportfölj','Inriktning mot tillverkning, grossist/distribution samt bygg och entreprenad','Arbetar från förstudie och implementation till vidareutveckling och förvaltning','Verksamhet från Jönköping, team om 1–10 personer'])
) AS v(pname, kd)
WHERE public.partners.name = v.pname
  AND (public.partners.key_differentiators IS NULL OR array_length(public.partners.key_differentiators, 1) IS NULL);