ALTER TABLE public.partners
  ADD COLUMN IF NOT EXISTS public_profile_summary text,
  ADD COLUMN IF NOT EXISTS public_focus_tags text[] NOT NULL DEFAULT '{}'::text[],
  ADD COLUMN IF NOT EXISTS public_topics_12m text[] NOT NULL DEFAULT '{}'::text[],
  ADD COLUMN IF NOT EXISTS public_profile_sources text[] NOT NULL DEFAULT '{}'::text[],
  ADD COLUMN IF NOT EXISTS public_profile_updated_at timestamptz;

CREATE OR REPLACE VIEW public.partners_public AS
 SELECT id,
    slug,
    name,
    description,
    logo_url,
    logo_dark_bg,
    website,
    email,
    contact_person,
    contact_photo_url,
    phone,
    applications,
    industries,
    secondary_industries,
    geography,
    product_filters,
    industry_apps,
    is_featured,
    customer_examples,
    office_cities,
    map_url,
    youtube_video_id,
    created_at,
    updated_at,
    industry_pitches,
    agreement_signed,
    related_party,
    positioning_statement,
    delivery_profile,
    team_size_sweden,
    implementations_done,
    not_a_fit,
    implementations_per_app,
    ai_summary,
    ai_summary_generated_at,
    ai_profile,
    extended_content,
    extended_content_updated_at,
    partner_size_tier,
    partner_size_tier_needs_review,
    ai_summary_full,
    best_fit_for,
    ai_tags,
    extended_competencies,
    team_size_per_app,
    key_differentiators,
    key_differentiators_source,
    public_profile_summary,
    public_focus_tags,
    public_topics_12m,
    public_profile_sources,
    public_profile_updated_at
   FROM partners
  WHERE is_featured = true;

GRANT SELECT ON public.partners_public TO anon, authenticated;