UPDATE public.partners p SET office_cities = v.cities, observed_locations = v.cities
FROM (VALUES
 ('accigo', ARRAY['Stockholm','Göteborg','Malmö']),
 ('active-business-solutions', ARRAY['Malmö']),
 ('acumant', ARRAY['Stockholm']),
 ('aperit', ARRAY['Värnamo']),
 ('apx-core-solutions', ARRAY['Kalmar']),
 ('avanade', ARRAY['Stockholm']),
 ('avega', ARRAY['Stockholm','Göteborg']),
 ('basecloud', ARRAY['Stockholm']),
 ('birdie-cloud', ARRAY['Stockholm']),
 ('brain-accounting', ARRAY['Stockholm']),
 ('exsitec', ARRAY['Linköping']),
 ('capgemini', ARRAY['Stockholm','Göteborg','Malmö']),
 ('cegeka', ARRAY['Stockholm','Linköping','Malmö']),
 ('cepheo', ARRAY['Stockholm','Göteborg','Malmö']),
 ('cgi', ARRAY['Stockholm','Göteborg','Malmö','Kalmar']),
 ('columbus-sweden-ab', ARRAY['Stockholm','Göteborg','Malmö','Jönköping']),
 ('compago', ARRAY['Malmö','Göteborg']),
 ('consid', ARRAY['Stockholm']),
 ('cosmo-consult', ARRAY['Stockholm','Göteborg','Malmö','Umeå']),
 ('dynamicskonsult', ARRAY['Stockholm']),
 ('engage-group', ARRAY['Stockholm','Göteborg','Malmö','Jönköping']),
 ('enqore-ab', ARRAY['Göteborg','Karlstad','Stockholm','Malmö','Linköping']),
 ('navipro-ab', ARRAY['Borås','Göteborg','Stockholm','Örebro']),
 ('ey', ARRAY['Stockholm','Göteborg']),
 ('fourone', ARRAY['Göteborg']),
 ('hay-it', ARRAY['Falkenberg']),
 ('implema', ARRAY['Stockholm','Göteborg','Malmö']),
 ('innofactor', ARRAY['Stockholm']),
 ('jma-maskindata', ARRAY['Eslöv']),
 ('kpmg', ARRAY['Stockholm','Göteborg']),
 ('mavrix', ARRAY['Stockholm']),
 ('midpoint-ab', ARRAY['Karlstad']),
 ('navet-ab', ARRAY['Helsingborg','Malmö','Mölndal','Stockholm']),
 ('nemely', ARRAY['Stockholm']),
 ('next365-group', ARRAY['Stockholm']),
 ('norteam', ARRAY['Stockholm','Göteborg','Västerås']),
 ('releye', ARRAY['Stockholm']),
 ('sandbox-republic', ARRAY['Stockholm']),
 ('sii-sverige', ARRAY['Stockholm']),
 ('sogeti', ARRAY['Stockholm','Göteborg','Malmö','Umeå','Linköping','Jönköping','Eskilstuna','Skellefteå','Helsingborg','Västerås','Borlänge','Uppsala']),
 ('sopra-steria', ARRAY['Stockholm','Göteborg','Malmö','Östersund']),
 ('sundet-crm', ARRAY['Malmö','Göteborg']),
 ('texus', ARRAY['Malmö']),
 ('thinknine', ARRAY['Malmö']),
 ('transformant', ARRAY['Stockholm']),
 ('united-hours', ARRAY['Stockholm','Kungälv']),
 ('update-affarssystem-ab', ARRAY['Göteborg']),
 ('xlent', ARRAY['Stockholm']),
 ('accenture', ARRAY['Stockholm']),
 ('azets', ARRAY['Stockholm','Göteborg','Malmö']),
 ('dizparc', ARRAY['Göteborg','Umeå','Malmö']),
 ('forefront-group', ARRAY['Stockholm']),
 ('fujitsu', ARRAY['Stockholm']),
 ('invid', ARRAY['Jönköping']),
 ('it-stod-ab', ARRAY['Skövde','Mariestad']),
 ('navcite', ARRAY['Luleå','Västerås']),
 ('norra-commerce-partner', ARRAY['Stockholm','Malmö']),
 ('pwc', ARRAY['Stockholm']),
 ('regentor', ARRAY['Göteborg']),
 ('softronic', ARRAY['Stockholm'])
) AS v(slug, cities)
WHERE p.slug = v.slug;

UPDATE public.partners
SET office_cities = ARRAY[]::text[]
WHERE slug IN ('ecit-sverige-ab','eg-sverige','hcl','hso','sa-global','future-it-partner');