UPDATE public.partners SET extended_content = 'Vivicta är en nordisk transformationspartner och större systemintegratör som levererar helhetsåtaganden inom Microsoft Dynamics 365. Bolaget har sitt ursprung i den tidigare Tietoevry Tech Services-verksamheten och verkar idag som en fristående aktör med huvudfokus på ERP & Applications, Data, Automation & AI, Cloud & Infrastructure samt Digital Security. Kombinationen av lokal närvaro i Norden och global leveranskapacitet gör Vivicta relevant för organisationer som söker en långsiktig partner för både implementation, förvaltning och modernisering av kritiska affärssystem.

Inom Dynamics 365 täcker Vivicta hela plattformen. De primära styrkeområdena ligger inom Finance & Supply Chain Management samt Customer Engagement/CRM, kompletterat med Business Central för medelstora bolag och Contact Center/Customer Service för kundtjänstintensiva verksamheter. Erbjudandet förstärks av Power Platform, Power BI/Fabric, Azure Integration Services och Microsoft 365/Copilot, vilket gör att Vivicta kan sätta ihop en sammanhållen Microsoft-stack snarare än enskilda punktlösningar. Sekundära områden inkluderar Project Operations, Human Resources och Field Service, samt bredare tjänster inom data, cloud, cybersecurity och managed services.

Målgruppen är främst midmarket, övre midmarket, enterprise och offentlig sektor. Vivicta tar även mindre Business Central-projekt inom utvalda nischer, men matchar särskilt väl när kunden behöver större kapacitet, flera länder, komplex integration, hög AI-mognad eller långsiktig förvaltning. Typiska uppdrag är ERP-moderniseringar, F&SCM-transformationer, CE/CRM-program, contact center-implementationer, integrationsplattformar samt data- och AI-initiativ. Bolaget positionerar sig som en partner för end-to-end digital transformation, från strategi och design till drift och kontinuerlig vidareutveckling.

Branschmässigt har Vivicta tydlig erfarenhet inom tillverkning, transport och logistik, industri- och serviceverksamhet med rental- eller equipment-inslag, skog, process och energi, offentlig sektor samt handel och service. På Business Central-sidan lyfts även telekom och IT-tjänster samt print- och grafisk produktion som områden där partnern har paketerad kunskap. För transport- och equipment-nära bolag finns dessutom erfarenhet av Annata A365, en branschlösning ovanpå Dynamics 365 för fordons-, utrustnings- och rentalindustri.

AI-mognaden bedöms som etablerad till hög. Vivicta kommunicerar en AI-first-ansats där Copilot, agentbaserad AI i ERP, AI i Dynamics 365 Contact Center och AI-drivna supply chain- och processflöden är centrala byggstenar. AI ses som en integrerad del av Dynamics 365 och den bredare Microsoft-stacken, snarare än som ett fristående sidospår. Kunder som redan står på Dynamics 365 kan därför nyttja Vivictas kompetens för att successivt införa Copilot, automation och agentflöden i befintliga processer.

Förvaltnings- och driftskapaciteten är hög. Vivicta är en av de större managed services-organisationerna i sitt segment och erbjuder support, applikationsförvaltning och drift av Dynamics 365 tillsammans med Azure-infrastruktur, integration och säkerhet. Den globala leveransmodellen, med resurser i bland annat Norden, Baltikum, Ukraina och Indien, gör det möjligt att skala team, hantera 24/7-behov och kombinera lokal rådgivning med kostnadseffektiv leverans i större program.

Särskiljande drag är kombinationen av nordisk lokal närhet, stor managed services-organisation, Microsoft Inner Circle-signal, bred täckning över D365 F&SCM och CE, uttalad AI- och agentagenda samt tillgång till branschnära lösningar inom transport, print och kontraktsfakturering. Vivicta är därför särskilt intressant för kunder som vill konsolidera fler områden hos en och samma partner och som värdesätter både bred plattformskompetens och långsiktig förvaltning.

Vivicta passar mindre bra som val när kunden söker en ren nischspecialist för en enskild mikrobransch eller ett litet, mycket standardiserat Business Central-projekt utan behov av bredare Microsoft- eller AI-kompetens. I sådana lägen kan mindre, mer fokuserade partners vara ett bättre alternativ. För organisationer som däremot står inför en större Dynamics 365-transformation, vill kombinera ERP, CRM, data och AI i ett sammanhållet program eller behöver en stabil långsiktig förvaltningspartner med nordisk och global leveransförmåga är Vivicta ett tungt vägande alternativ.' WHERE id = 'cfe135f8-b2bf-4740-9f26-389bca040715';