-- Partnergranskningsalternativ för F&SCM och CRM (sales, customer-insights, service-produkter).
-- Idempotent: befintliga rader påverkas inte.

insert into product_attribute_options (product_id, dimension_key, attribute_key, label, sort_order)
select c.id, v.dimension_key, v.attribute_key, v.label, v.sort_order
from (values
('contact-center','competency','case_management','Ärendehantering',100),
('contact-center','competency','csat','Kundnöjdhet och uppföljning',100),
('contact-center','competency','field_service','Fältservice och arbetsorder',100),
('contact-center','competency','integrations_api','Integrationer och API',100),
('contact-center','competency','knowledge_base','Kunskapsbas och självservice',100),
('contact-center','competency','omnichannel','Flera kanaler (chat, telefon, e-post)',100),
('contact-center','competency','scheduling','Schemaläggning och resursplanering',100),
('contact-center','competency','sla_queues','SLA och ärendeköer',100),
('contact-center','delivery_model','fixed_price_start','Fastprisstart',100),
('contact-center','delivery_model','maintenance_partner','Förvaltningspartner',100),
('contact-center','delivery_model','managed_services','Managed Services',100),
('contact-center','delivery_model','phased_implementation','Successiv implementation',100),
('contact-center','delivery_model','proof_of_concept','Proof of Concept',100),
('contact-center','delivery_model','quickstart_package','Snabbstartspaket',100),
('contact-center','delivery_model','traditional_project','Traditionellt implementationsprojekt',100),
('contact-center','migration','dynamics_crm','Dynamics CRM (äldre)',100),
('contact-center','migration','freshdesk','Freshdesk',100),
('contact-center','migration','other_service_system','Annat system',100),
('contact-center','migration','salesforce_service','Salesforce Service Cloud',100),
('contact-center','migration','spreadsheets','E-post och kalkylblad',100),
('contact-center','migration','zendesk','Zendesk',100),
('contact-center','project_type','international_rollout','Internationell utrullning',100),
('contact-center','project_type','maintenance_support','Förvaltning och support',100),
('contact-center','project_type','migration','Migrering',100),
('contact-center','project_type','multi_company_implementation','Flerbolagsimplementation',100),
('contact-center','project_type','new_implementation','Nyimplementation',100),
('contact-center','project_type','rescue','Rescue-projekt',100),
('contact-center','project_type','system_consolidation','Konsolidering av flera system',100),
('contact-center','project_type','upgrade','Uppgradering',100),
('customer-insights','competency','customer_data','Kunddata och segmentering',100),
('customer-insights','competency','forecasting','Prognos och försäljningsstyrning',100),
('customer-insights','competency','integrations_api','Integrationer (ERP, Outlook, Teams)',100),
('customer-insights','competency','marketing','Marknadsföring och kampanjer',100),
('customer-insights','competency','quoting','Offerter och prislistor',100),
('customer-insights','competency','reporting','Rapportering och analys',100),
('customer-insights','competency','sales_process','Försäljningsprocess och pipeline',100),
('customer-insights','delivery_model','fixed_price_start','Fastprisstart',100),
('customer-insights','delivery_model','maintenance_partner','Förvaltningspartner',100),
('customer-insights','delivery_model','managed_services','Managed Services',100),
('customer-insights','delivery_model','phased_implementation','Successiv implementation',100),
('customer-insights','delivery_model','proof_of_concept','Proof of Concept',100),
('customer-insights','delivery_model','quickstart_package','Snabbstartspaket',100),
('customer-insights','delivery_model','traditional_project','Traditionellt implementationsprojekt',100),
('customer-insights','migration','dynamics_crm','Dynamics CRM (äldre)',100),
('customer-insights','migration','hubspot','HubSpot',100),
('customer-insights','migration','lime','LIME',100),
('customer-insights','migration','other_crm','Annat CRM',100),
('customer-insights','migration','salesforce','Salesforce',100),
('customer-insights','migration','spreadsheets','Kalkylblad / egna listor',100),
('customer-insights','migration','superoffice','SuperOffice',100),
('customer-insights','project_type','international_rollout','Internationell utrullning',100),
('customer-insights','project_type','maintenance_support','Förvaltning och support',100),
('customer-insights','project_type','migration','Migrering',100),
('customer-insights','project_type','multi_company_implementation','Flerbolagsimplementation',100),
('customer-insights','project_type','new_implementation','Nyimplementation',100),
('customer-insights','project_type','rescue','Rescue-projekt',100),
('customer-insights','project_type','system_consolidation','Konsolidering av flera system',100),
('customer-insights','project_type','upgrade','Uppgradering',100),
('customer-service','competency','case_management','Ärendehantering',100),
('customer-service','competency','csat','Kundnöjdhet och uppföljning',100),
('customer-service','competency','field_service','Fältservice och arbetsorder',100),
('customer-service','competency','integrations_api','Integrationer och API',100),
('customer-service','competency','knowledge_base','Kunskapsbas och självservice',100),
('customer-service','competency','omnichannel','Flera kanaler (chat, telefon, e-post)',100),
('customer-service','competency','scheduling','Schemaläggning och resursplanering',100),
('customer-service','competency','sla_queues','SLA och ärendeköer',100),
('customer-service','delivery_model','fixed_price_start','Fastprisstart',100),
('customer-service','delivery_model','maintenance_partner','Förvaltningspartner',100),
('customer-service','delivery_model','managed_services','Managed Services',100),
('customer-service','delivery_model','phased_implementation','Successiv implementation',100),
('customer-service','delivery_model','proof_of_concept','Proof of Concept',100),
('customer-service','delivery_model','quickstart_package','Snabbstartspaket',100),
('customer-service','delivery_model','traditional_project','Traditionellt implementationsprojekt',100),
('customer-service','migration','dynamics_crm','Dynamics CRM (äldre)',100),
('customer-service','migration','freshdesk','Freshdesk',100),
('customer-service','migration','other_service_system','Annat system',100),
('customer-service','migration','salesforce_service','Salesforce Service Cloud',100),
('customer-service','migration','spreadsheets','E-post och kalkylblad',100),
('customer-service','migration','zendesk','Zendesk',100),
('customer-service','project_type','international_rollout','Internationell utrullning',100),
('customer-service','project_type','maintenance_support','Förvaltning och support',100),
('customer-service','project_type','migration','Migrering',100),
('customer-service','project_type','multi_company_implementation','Flerbolagsimplementation',100),
('customer-service','project_type','new_implementation','Nyimplementation',100),
('customer-service','project_type','rescue','Rescue-projekt',100),
('customer-service','project_type','system_consolidation','Konsolidering av flera system',100),
('customer-service','project_type','upgrade','Uppgradering',100),
('field-service','competency','case_management','Ärendehantering',100),
('field-service','competency','csat','Kundnöjdhet och uppföljning',100),
('field-service','competency','field_service','Fältservice och arbetsorder',100),
('field-service','competency','integrations_api','Integrationer och API',100),
('field-service','competency','knowledge_base','Kunskapsbas och självservice',100),
('field-service','competency','omnichannel','Flera kanaler (chat, telefon, e-post)',100),
('field-service','competency','scheduling','Schemaläggning och resursplanering',100),
('field-service','competency','sla_queues','SLA och ärendeköer',100),
('field-service','delivery_model','fixed_price_start','Fastprisstart',100),
('field-service','delivery_model','maintenance_partner','Förvaltningspartner',100),
('field-service','delivery_model','managed_services','Managed Services',100),
('field-service','delivery_model','phased_implementation','Successiv implementation',100),
('field-service','delivery_model','proof_of_concept','Proof of Concept',100),
('field-service','delivery_model','quickstart_package','Snabbstartspaket',100),
('field-service','delivery_model','traditional_project','Traditionellt implementationsprojekt',100),
('field-service','migration','dynamics_crm','Dynamics CRM (äldre)',100),
('field-service','migration','freshdesk','Freshdesk',100),
('field-service','migration','other_service_system','Annat system',100),
('field-service','migration','salesforce_service','Salesforce Service Cloud',100),
('field-service','migration','spreadsheets','E-post och kalkylblad',100),
('field-service','migration','zendesk','Zendesk',100),
('field-service','project_type','international_rollout','Internationell utrullning',100),
('field-service','project_type','maintenance_support','Förvaltning och support',100),
('field-service','project_type','migration','Migrering',100),
('field-service','project_type','multi_company_implementation','Flerbolagsimplementation',100),
('field-service','project_type','new_implementation','Nyimplementation',100),
('field-service','project_type','rescue','Rescue-projekt',100),
('field-service','project_type','system_consolidation','Konsolidering av flera system',100),
('field-service','project_type','upgrade','Uppgradering',100),
('finance','competency','distribution_wholesale','Distribution och grossist',100),
('finance','competency','edi','EDI',100),
('finance','competency','finance_accounting','Ekonomi och redovisning',100),
('finance','competency','integrations_api','Integrationer och API',100),
('finance','competency','international','Internationell verksamhet',100),
('finance','competency','manufacturing','Produktion och tillverkning',100),
('finance','competency','multi_company','Flerbolagsmiljö',100),
('finance','competency','projects','Projektverksamhet',100),
('finance','competency','purchasing','Inköp',100),
('finance','competency','retail_ecommerce','Retail och e-handel',100),
('finance','competency','sales_order','Försäljning och order',100),
('finance','competency','service_management','Servicehantering',100),
('finance','competency','supply_chain_planning','Planering (demand/supply)',100),
('finance','competency','warehouse_logistics','Lager och logistik',100),
('finance','delivery_model','fixed_price_start','Fastprisstart',100),
('finance','delivery_model','maintenance_partner','Förvaltningspartner',100),
('finance','delivery_model','managed_services','Managed Services',100),
('finance','delivery_model','phased_implementation','Successiv implementation',100),
('finance','delivery_model','proof_of_concept','Proof of Concept',100),
('finance','delivery_model','quickstart_package','Snabbstartspaket',100),
('finance','delivery_model','traditional_project','Traditionellt implementationsprojekt',100),
('finance','migration','ax','Dynamics AX / D365 FO (lokalt)',100),
('finance','migration','fortnox','Fortnox',100),
('finance','migration','ifs','IFS',100),
('finance','migration','jeeves','Jeeves',100),
('finance','migration','monitor','Monitor ERP',100),
('finance','migration','nav','NAV / Navision',100),
('finance','migration','oracle_netsuite','Oracle / NetSuite',100),
('finance','migration','other_erp','Annat ERP',100),
('finance','migration','pyramid','Pyramid',100),
('finance','migration','sap','SAP ECC / S/4HANA',100),
('finance','migration','sap_business_one','SAP Business One',100),
('finance','migration','visma','Visma',100),
('finance','project_type','international_rollout','Internationell utrullning',100),
('finance','project_type','maintenance_support','Förvaltning och support',100),
('finance','project_type','migration','Migrering',100),
('finance','project_type','multi_company_implementation','Flerbolagsimplementation',100),
('finance','project_type','new_implementation','Nyimplementation',100),
('finance','project_type','rescue','Rescue-projekt',100),
('finance','project_type','system_consolidation','Konsolidering av flera system',100),
('finance','project_type','upgrade','Uppgradering',100),
('sales','competency','customer_data','Kunddata och segmentering',100),
('sales','competency','forecasting','Prognos och försäljningsstyrning',100),
('sales','competency','integrations_api','Integrationer (ERP, Outlook, Teams)',100),
('sales','competency','marketing','Marknadsföring och kampanjer',100),
('sales','competency','quoting','Offerter och prislistor',100),
('sales','competency','reporting','Rapportering och analys',100),
('sales','competency','sales_process','Försäljningsprocess och pipeline',100),
('sales','delivery_model','fixed_price_start','Fastprisstart',100),
('sales','delivery_model','maintenance_partner','Förvaltningspartner',100),
('sales','delivery_model','managed_services','Managed Services',100),
('sales','delivery_model','phased_implementation','Successiv implementation',100),
('sales','delivery_model','proof_of_concept','Proof of Concept',100),
('sales','delivery_model','quickstart_package','Snabbstartspaket',100),
('sales','delivery_model','traditional_project','Traditionellt implementationsprojekt',100),
('sales','migration','dynamics_crm','Dynamics CRM (äldre)',100),
('sales','migration','hubspot','HubSpot',100),
('sales','migration','lime','LIME',100),
('sales','migration','other_crm','Annat CRM',100),
('sales','migration','salesforce','Salesforce',100),
('sales','migration','spreadsheets','Kalkylblad / egna listor',100),
('sales','migration','superoffice','SuperOffice',100),
('sales','project_type','international_rollout','Internationell utrullning',100),
('sales','project_type','maintenance_support','Förvaltning och support',100),
('sales','project_type','migration','Migrering',100),
('sales','project_type','multi_company_implementation','Flerbolagsimplementation',100),
('sales','project_type','new_implementation','Nyimplementation',100),
('sales','project_type','rescue','Rescue-projekt',100),
('sales','project_type','system_consolidation','Konsolidering av flera system',100),
('sales','project_type','upgrade','Uppgradering',100),
('supply-chain','competency','distribution_wholesale','Distribution och grossist',100),
('supply-chain','competency','edi','EDI',100),
('supply-chain','competency','finance_accounting','Ekonomi och redovisning',100),
('supply-chain','competency','integrations_api','Integrationer och API',100),
('supply-chain','competency','international','Internationell verksamhet',100),
('supply-chain','competency','manufacturing','Produktion och tillverkning',100),
('supply-chain','competency','multi_company','Flerbolagsmiljö',100),
('supply-chain','competency','projects','Projektverksamhet',100),
('supply-chain','competency','purchasing','Inköp',100),
('supply-chain','competency','retail_ecommerce','Retail och e-handel',100),
('supply-chain','competency','sales_order','Försäljning och order',100),
('supply-chain','competency','service_management','Servicehantering',100),
('supply-chain','competency','supply_chain_planning','Planering (demand/supply)',100),
('supply-chain','competency','warehouse_logistics','Lager och logistik',100),
('supply-chain','delivery_model','fixed_price_start','Fastprisstart',100),
('supply-chain','delivery_model','maintenance_partner','Förvaltningspartner',100),
('supply-chain','delivery_model','managed_services','Managed Services',100),
('supply-chain','delivery_model','phased_implementation','Successiv implementation',100),
('supply-chain','delivery_model','proof_of_concept','Proof of Concept',100),
('supply-chain','delivery_model','quickstart_package','Snabbstartspaket',100),
('supply-chain','delivery_model','traditional_project','Traditionellt implementationsprojekt',100),
('supply-chain','migration','ax','Dynamics AX / D365 FO (lokalt)',100),
('supply-chain','migration','fortnox','Fortnox',100),
('supply-chain','migration','ifs','IFS',100),
('supply-chain','migration','jeeves','Jeeves',100),
('supply-chain','migration','monitor','Monitor ERP',100),
('supply-chain','migration','nav','NAV / Navision',100),
('supply-chain','migration','oracle_netsuite','Oracle / NetSuite',100),
('supply-chain','migration','other_erp','Annat ERP',100),
('supply-chain','migration','pyramid','Pyramid',100),
('supply-chain','migration','sap','SAP ECC / S/4HANA',100),
('supply-chain','migration','sap_business_one','SAP Business One',100),
('supply-chain','migration','visma','Visma',100),
('supply-chain','project_type','international_rollout','Internationell utrullning',100),
('supply-chain','project_type','maintenance_support','Förvaltning och support',100),
('supply-chain','project_type','migration','Migrering',100),
('supply-chain','project_type','multi_company_implementation','Flerbolagsimplementation',100),
('supply-chain','project_type','new_implementation','Nyimplementation',100),
('supply-chain','project_type','rescue','Rescue-projekt',100),
('supply-chain','project_type','system_consolidation','Konsolidering av flera system',100),
('supply-chain','project_type','upgrade','Uppgradering',100)
) as v(product_key, dimension_key, attribute_key, label, sort_order)
join product_catalog c on c.product_key = v.product_key
on conflict (product_id, dimension_key, attribute_key) do nothing;
